# ============================================================
# Rule: qc_report_post
# Generates a QC HTML, PDF, and cell-metrics CSV report AFTER filtering.
# ============================================================

rule qc_report_post:
    input:
        h5ad     = os.path.join(FILT_DIR, "{sample}_filtered.h5ad"),
        metadata = config["input"]["metadata"],
        cfg      = "config/config.yaml",
    output:
        # ── TRACK ALL THREE OUTPUTS GENERATED BY THE SCRIPT ──
        html = os.path.join(QC_DIR, "post_{sample}_qc.html"),
        pdf  = os.path.join(QC_DIR, "post_{sample}_qc.pdf"),
        csv  = os.path.join(QC_DIR, "post_{sample}_cell_qc_metrics.csv")
    params:
        sample_id = "{sample}",
        stage     = "post",
    conda:
        "../envs/scanpy.yaml"
    log:
        "logs/qc/post_{sample}.log"
    shell:
        """
        python workflow/scripts/01_qc_stats_report.py \
            --input     "{input.h5ad}"       \
            --metadata  "{input.metadata}"   \
            --cfg       "{input.cfg}"        \
            --sample_id "{params.sample_id}" \
            --stage     "{params.stage}"     \
            --output    "{output.html}"      \
        > {log} 2>&1
        """