# Pipeline Configuration

# SPECIES

species: "human"

#  INPUT 
input:
  # Sample sheet mapping sample IDs paths and metadata
  samples: "config/samples.csv"

#  OUTPUT
output:
  soupx_dir:          "results/01_soupx/files"
  qc_pre_dir:         "results/02_qc_pre/files"
  multiqc_pre_dir:    "results/03_multiqc_pre/files"
  multiqc_post_dir:   "results/04_multiqc_post/files"
  filtered_dir:       "results/05_filtering/files"
  qc_post_dir:        "results/06_qc_post/files"
  merge_dir:          "results/07_merge/files"
  facs_dir:           "results/08_remove_facs_contamination/files"
  harmony_dir:        "results/09_harmony/files"
  clustering_dir:     "results/10_clustering/files"
  celltypist_dir:     "results/11_celltypist/files"

# QC report plot settings
qc_plots:
  color_by:
    - fraction
    - sex
    - response_type


#  Doublet Detection 
doublets:
  run_scrublet:  true
  expected_rate: 0.05  

# union or intersection of genes when merging
merge:
  join: "union"

# Ambient RNA correction
# If true, QC and filtering use the SoupX-corrected .h5ad files as input.
# If false, they use the original count matrices from the sample sheet.
soupx:
  use_soupx: true
  soupgenes: "config/soupgenes.txt" # genes used as soup
  apply_to_fractions: ["IMMUNE"] # apply soupx to this fraction 

# Preprocessing
pp:
  scale: false
  normalize: total_counts
  factor: 10000

# Harmony integration
harmony:
  run_harmony: true
  integration_keys:
    - sample_id
  n_pcs: 20
  thetas: null      

# Clustering
clustering:
  use_harmony:     true
  resolution_test: [.1,.2,.3,.4,.5,.6,.7,.8,0.9,1]
  seed: 42
  marker_file: "config/markers.csv"   # two columns: gene, cell_state

# remove facs contamination
non_sorted_flag: "Non-sorted"
immune_label:    "IMMUNE"
epidn_label:     "EPI+DN"

# CellTypist annotation
celltypist:
  model: null       # null → uses species default (mouse: Adult_Mouse_Gut, human: Cells_Intestinal_Tract)
  leiden_key: null   # leiden key for crosstab vs celltypist labels