# Pipeline Configuration

# SPECIES

species: "human"

#  INPUT 
input:
  # Sample sheet mapping sample IDs paths and metadata
  samples: "config/samples.csv"

#  OUTPUT
output:
  soupx_dir:          "results/01_soupx"
  qc_pre_dir:         "results/02_qc_pre"
  multiqc_pre_dir:    "results/03_multiqc_pre"
  multiqc_post_dir:   "results/04_multiqc_post"
  filtered_dir:       "results/05_filtering"
  qc_post_dir:        "results/06_qc_post"
  merge_dir:          "results/07_merge"
  facs_dir:           "results/08_remove_facs_contamination"
  harmony_dir:        "results/09_harmony"
  clustering_dir:     "results/10_clustering"
  celltypist_dir:     "results/11_celltypist"

# QC report plot settings
qc_plots:
  color_by:
    - fraction
    - sex
    - response_type


#  Doublet Detection
doublets:
  run_scrublet:    true
  expected_rate:   0.05
  remove_doublets: true   # if true, doublets are removed during the filter step

#  Gene filtering
filter_genes:
  remove_mt:     true   # remove mitochondrial genes
  remove_ribo:   true   # remove ribosomal genes
  remove_malat1: true   # remove MALAT1

# union or intersection of genes when merging
merge:
  join: "union"

# Ambient RNA correction
# If true, QC and filtering use the SoupX-corrected .h5ad files as input.
# If false, they use the original count matrices from the sample sheet.
soupx:
  use_soupx: true
  soupgenes: "config/soupgenes.txt" # genes used as soup
  apply_to_fractions: ["IMMUNE"] # apply soupx to this fraction 

# Preprocessing
pp:
  scale: false
  normalize: total_counts
  factor: 10000

# Harmony integration
harmony:
  run_harmony: true
  integration_keys:
    - sample_id
  n_pcs: 20
  thetas: null      

# Clustering
clustering:
  use_harmony:     true
  resolution_test: [.1,.2,.3,.4,.5,.6,.7,.8,0.9,1]
  seed: 42
  marker_file: "config/markers.csv"   # two columns: gene, cell_state

# remove facs contamination
non_sorted_flag: "Non-sorted"
immune_label:    "IMMUNE"
epidn_label:     "EPI+DN"
remove_clusters: []   # leiden_contam cluster IDs to drop entirely, e.g. [3, 7]

# CellTypist annotation
celltypist:
  model: null       # null → uses species default (mouse: Adult_Mouse_Gut, human: Cells_Intestinal_Tract)
  leiden_key: null   # leiden key for crosstab vs celltypist labels