# Pipeline Configuration

#  INPUT 
input:
  # Sample sheet mapping sample IDs to their paths
  sample_sheet: "config/samples.csv"

  # Experimental metadata (conditions, batches, etc.) for downstream analysis
  metadata: "config/metadata.csv"

#  OUTPUT
output:
  qc_dir:         "results/qc/"
  filtered_dir:   "results/filtered/"
  integrated_dir: "results/integrated/"
  soupx_dir:      "results/01_soupx/files"
  merge_dir:      "results/03_merge_adatas/files"

#  QC Thresholds 
qc_thresholds:
  min_genes:          200   
  max_genes:          6000  
  min_counts:         500   
  max_pct_mt:         20    
  min_cells_per_gene: 3     

#  Doublet Detection 
doublets:
  run_scrublet:          true
  expected_doublet_rate: 0.05

# union or intersection of genes when merging
merge:
  join: "union"

# Ambient RNA correction
# If true, QC and filtering use the SoupX-corrected .h5ad files as input.
# If false, they use the original count matrices from the sample sheet.
soupx:
  use_soupx: false